// CSOH Website - Interactive JavaScript

// Debounce function for performance optimization
function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// Cache frequently accessed DOM elements
const domCache = {
    searchInput: null,
    categoryHeaders: null,
    cards: null
};

function sanitize(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

document.addEventListener('DOMContentLoaded', function() {
    document.body.classList.add('js-enabled');

    // Initialize DOM cache
    domCache.searchInput = document.getElementById('searchInput');
    domCache.categoryHeaders = document.querySelectorAll('.category-section h3');
    domCache.cards = document.querySelectorAll('.resource-card');

    // Dark mode initialization
    initThemeToggle();

    // Search suggestions initialization
    initSearchSuggestions();

    // Social sharing buttons (news page)
    initShareButtons();

    // Enforce rel attributes on external links opened in new tabs.
    document.querySelectorAll('a[target="_blank"]').forEach(link => {
        const rel = (link.getAttribute('rel') || '').split(' ').filter(Boolean);
        if (!rel.includes('noopener')) rel.push('noopener');
        if (!rel.includes('noreferrer')) rel.push('noreferrer');
        link.setAttribute('rel', rel.join(' '));
    });

    // Hamburger menu toggle
    const hamburger = document.querySelector('.hamburger');
    if (hamburger) {
        hamburger.addEventListener('click', function () {
            const isOpen = document.body.classList.toggle('nav-open');
            this.setAttribute('aria-expanded', String(isOpen));
            this.textContent = isOpen ? '✕' : '☰';
        });
    }

    // Add accessible label for search input
    if (domCache.searchInput && !document.querySelector('label[for="searchInput"]')) {
        const label = document.createElement('label');
        label.setAttribute('for', 'searchInput');
        label.className = 'visually-hidden';
        label.textContent = 'Search resources';
        domCache.searchInput.parentNode.insertBefore(label, domCache.searchInput);
    }
    
    // Add icons to resource cards
    addIconsToCards();

    // Load preview mapping (generated by tools/generate_previews.py) then add previews
    loadPreviewMap().then(() => {
        addPreviewImagesToCards();
    });
    
    // Show All Articles button
    const showAllBtn = document.getElementById('showAllBtn');
    if (showAllBtn) {
        showAllBtn.addEventListener('click', () => {
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            // Remove active state from all tag filters
            document.querySelectorAll('.filter-btn').forEach(btn => {
                btn.classList.remove('active');
            });
            // Show all cards
            const cards = document.querySelectorAll('.resource-card');
            cards.forEach(card => {
                getToggleTarget(card).style.display = '';
            });
            updateVisibleCount();
        });
    }

    // Search functionality with debounce for better performance
    if (domCache.searchInput) {
        const params = new URLSearchParams(window.location.search);
        const query = sanitize(params.get('q') || '');
        if (query) {
            domCache.searchInput.value = query;
            filterResources(query.toLowerCase());
        }

        // Support ?category= URL parameter for deep-linking from footer/nav
        const categoryParam = params.get('category');
        const validCategories = ['all', 'ctf', 'tool', 'certification', 'lab', 'ai-security', 'job', 'new'];
        if (categoryParam && !query && validCategories.includes(categoryParam)) {
            // Defer to allow DOM to fully settle (tag filters, card icons, etc.)
            setTimeout(function() {
                // Activate the matching filter button
                document.querySelectorAll('button[data-category]').forEach(function(b) {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                var btn = document.querySelector('button[data-category="' + categoryParam + '"]');
                if (btn) {
                    btn.classList.add('active');
                    btn.setAttribute('aria-pressed', 'true');
                }
                // Apply the filter
                if (categoryParam === 'all') {
                    document.querySelectorAll('.resource-card').forEach(function(card) {
                        getToggleTarget(card).style.display = '';
                    });
                } else if (categoryParam === 'new') {
                    filterByTagText('new');
                } else {
                    filterBySection(categoryParam);
                }
                updateVisibleCount();
            }, 50);
        }

        const debouncedSearch = debounce(function(e) {
            const searchTerm = e.target.value.toLowerCase();
            filterResources(searchTerm);
        }, 150);
        domCache.searchInput.addEventListener('input', debouncedSearch);
    }

    // Category filter buttons - direct attachment for better mobile support
    const categoryButtons = document.querySelectorAll('button[data-category]:not(.tag-filter)');
    categoryButtons.forEach(btn => {
        btn.addEventListener('click', function(e) {
            e.preventDefault();
            const category = this.dataset.category;
            
            // Remove active class from all category buttons
            document.querySelectorAll('button[data-category]:not(.tag-filter)').forEach(b => {
                b.classList.remove('active');
                b.setAttribute('aria-pressed', 'false');
            });
            
            // Add active class to clicked button
            this.classList.add('active');
            this.setAttribute('aria-pressed', 'true');
            
            // Clear search input
            if (domCache.searchInput) {
                domCache.searchInput.value = '';
            }
            
            // Filter by category
            if (category === 'all') {
                // Show all cards
                const cards = document.querySelectorAll('.resource-card');
                cards.forEach(card => {
                    getToggleTarget(card).style.display = '';
                });
            } else if (category === 'new') {
                // Filter by 'new' tag
                filterByTagText('new');
            } else {
                // Filter by section (ctf, tool, certification, lab, ai-security, job)
                filterBySection(category);
            }
            
            updateVisibleCount();
        });
    });

    // Category collapse/expand - use event delegation
    const mainContent = document.getElementById('main-content');
    if (mainContent) {
        // Initialize ARIA attributes on category headers
        document.querySelectorAll('.category-section h3').forEach(header => {
            header.setAttribute('role', 'button');
            header.setAttribute('tabindex', '0');
            const isCollapsed = header.parentElement.classList.contains('collapsed');
            header.setAttribute('aria-expanded', String(!isCollapsed));
        });

        mainContent.addEventListener('click', function(e) {
            const header = e.target.closest('.category-section h3');
            if (header && header.parentElement.classList.contains('category-section')) {
                header.parentElement.classList.toggle('collapsed');
                const isCollapsed = header.parentElement.classList.contains('collapsed');
                header.setAttribute('aria-expanded', String(!isCollapsed));
            }
        });

        // Keyboard support: Enter/Space to toggle
        mainContent.addEventListener('keydown', function(e) {
            if (e.key === 'Enter' || e.key === ' ') {
                const header = e.target.closest('.category-section h3');
                if (header && header.parentElement.classList.contains('category-section')) {
                    e.preventDefault();
                    header.click();
                }
            }
        });
    }

    // Card click functionality is now handled via HTML <a> wrapper

    // Smooth scrolling for anchor links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function(e) {
            e.preventDefault();
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                target.scrollIntoView({
                    behavior: 'smooth',
                    block: 'start'
                });
            }
        });
    });
    // Initialize dynamic tag filters and visible count on load
    if (typeof generateTagFilters === 'function') generateTagFilters();
    if (typeof updateVisibleCount === 'function') updateVisibleCount();
});

// Generate tag filter buttons dynamically from tags on the page
function generateTagFilters() {
    const container = document.getElementById('allTagsContainer');
    if (!container) return;
    container.innerHTML = '';

    // Count occurrences of each tag text
    const tagNodes = Array.from(document.querySelectorAll('.resource-card .tag'));
    const counts = {};
    tagNodes.forEach(t => {
        const txt = t.textContent.trim();
        if (!txt) return;
        counts[txt] = (counts[txt] || 0) + 1;
    });

    // Sort tags by frequency (descending), tiebreak alphabetically
    const sortedTags = Object.keys(counts).sort((a, b) => {
        const diff = counts[b] - counts[a];
        return diff !== 0 ? diff : a.localeCompare(b);
    });

    // Track expanded state
    let isExpanded = false;
    const TOP_N = 20;

    // Function to render tags (top N or all)
    const renderTags = (showAll = false) => {
        // Clear existing buttons but keep toggle button if visible
        Array.from(container.querySelectorAll('.tag-filter')).forEach(btn => btn.remove());
        Array.from(container.querySelectorAll('.toggle-tags-btn')).forEach(btn => btn.remove());

        const tagsToRender = showAll ? sortedTags : sortedTags.slice(0, TOP_N);

        tagsToRender.forEach(tagText => {
            const btn = document.createElement('button');
            btn.className = 'filter-btn tag-filter';
            btn.dataset.tag = tagText;
            btn.textContent = `${tagText} (${counts[tagText]})`;
            btn.title = `${counts[tagText]} resources`;
            btn.addEventListener('click', function() {
                // clear other active buttons
                document.querySelectorAll('.filter-btn').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                document.querySelectorAll('.tag-filter').forEach(b => {
                    b.classList.remove('active');
                    b.setAttribute('aria-pressed', 'false');
                });
                this.classList.add('active');
                this.setAttribute('aria-pressed', 'true');
                filterByTagText(tagText);
            });
            container.appendChild(btn);
        });

        // Add toggle button if there are more tags than TOP_N
        if (sortedTags.length > TOP_N) {
            const toggleBtn = document.createElement('button');
            toggleBtn.className = 'filter-btn toggle-tags-btn';
            toggleBtn.textContent = showAll ? `Show fewer tags (${TOP_N})` : `Show all tags (${sortedTags.length})`;
            toggleBtn.addEventListener('click', function() {
                isExpanded = !isExpanded;
                renderTags(isExpanded);
            });
            container.appendChild(toggleBtn);
        }
    };

    // Initial render: top N tags only
    renderTags(false);
}

let previewMap = {};

function loadPreviewMap() {
    return fetch('preview-mapping.json')
        .then(resp => {
            if (!resp.ok) return {};
            return resp.json();
        })
        .then(json => {
            previewMap = json || {};
        })
        .catch(() => { previewMap = {}; });
}

// Filter cards by tag text (case-insensitive)
function filterByTagText(tagText) {
    const search = tagText.toLowerCase();
    const cards = document.querySelectorAll('.resource-card');
    cards.forEach(card => {
        const tags = Array.from(card.querySelectorAll('.tag')).map(t => t.textContent.toLowerCase()).join(' ');
        getToggleTarget(card).style.display = tags.includes(search) ? '' : 'none';
    });
    updateVisibleCount();
}

// Map category button values to their section IDs in resources.html
const categorySectionMap = {
    'ctf': 'ctf-challenges',
    'tool': 'security-tools',
    'certification': 'certifications',
    'lab': 'labs-training',
    'ai-security': 'ai-security',
    'job': 'job-search'
};

function filterBySection(category) {
    const sectionId = categorySectionMap[category];
    if (!sectionId) return;
    const cards = document.querySelectorAll('.resource-card');
    cards.forEach(card => {
        const section = card.closest('.category-section');
        const inSection = section && section.id === sectionId;
        getToggleTarget(card).style.display = inSection ? '' : 'none';
    });
    updateVisibleCount();
}

function addIconsToCards() {
    const cards = document.querySelectorAll('.resource-card');
    
    cards.forEach(card => {
        // Check if icon already exists
        if (card.querySelector('.resource-card-icon')) return;
        
        const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase());
        const title = card.querySelector('h3').textContent.toLowerCase();
        
        let icon = '🔐'; // default security icon
        let iconClass = '';
        
        // Determine icon based on tags and content
        if (tags.some(tag => tag.includes('ctf')) || title.includes('ctf') || title.includes('goat') || title.includes('vulnerable')) {
            icon = '🎯';
            iconClass = 'ctf';
        } else if (tags.some(tag => tag.includes('tool')) || tags.some(tag => tag.includes('cspm')) || tags.some(tag => tag.includes('cnapp'))) {
            icon = '🛠️';
            iconClass = 'tool';
        } else if (tags.some(tag => tag.includes('certification')) || title.includes('cert')) {
            icon = '🎓';
            iconClass = 'certification';
        } else if (tags.some(tag => tag.includes('lab') || tag.includes('hands-on') || tag.includes('training'))) {
            icon = '🧪';
            iconClass = 'lab';
        } else if (tags.some(tag => tag.includes('kubernetes') || tag.includes('k8s')) || title.includes('kubernetes')) {
            icon = '☸️';
            iconClass = 'kubernetes';
        } else if (tags.some(tag => tag.includes('ai') || tag.includes('ml')) || title.includes('ai')) {
            icon = '🤖';
            iconClass = 'ai';
        } else if (title.includes('aws')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('azure')) {
            icon = '☁️';
            iconClass = 'tool';
        } else if (title.includes('gcp') || title.includes('google cloud')) {
            icon = '☁️';
            iconClass = 'tool';
        }
        
        // Create icon element
        const iconDiv = document.createElement('div');
        iconDiv.className = `resource-card-icon ${iconClass}`;
        iconDiv.textContent = icon;
        
        // Insert icon at the beginning of the card
        card.insertBefore(iconDiv, card.firstChild);
    });
}

// Insert a small preview screenshot for each resource card.
// Uses WordPress mShots service to generate a lightweight thumbnail.
function addPreviewImagesToCards() {
    const cards = document.querySelectorAll('.resource-card');

    cards.forEach(card => {
        // Skip if card marked as no-preview (e.g., index page category cards)
        if (card.hasAttribute('data-no-preview')) return;
        
        // avoid duplicating previews
        if (card.querySelector('.resource-preview')) return;

        const link = card.querySelector('h3 a');
        if (!link) return;

        const url = link.href;
        if (!url) return;

        const img = document.createElement('img');
        img.className = 'resource-preview';
        img.alt = `Preview of ${link.textContent.trim()}`;
        img.loading = 'lazy';
        img.referrerPolicy = 'no-referrer';
        img.decoding = 'async';
        // Set explicit dimensions to prevent layout shift
        img.width = 600;
        img.height = 160;


        // Use local preview when available; otherwise fall back to remote mShots.
        if (previewMap[url]) {
            img.src = previewMap[url];
            img.onerror = function() { img.remove(); };
        } else {
            // fallback to mShots for sites without local previews
            img.src = `https://s.wordpress.com/mshots/v1/${encodeURIComponent(url)}?w=600`;
            // remove the image if it fails to load or appears to be a tiny placeholder
            img.onerror = function() { img.remove(); };
            img.onload = function() {
                try {
                    if ((img.naturalWidth && img.naturalWidth < 50) || (img.naturalHeight && img.naturalHeight < 50)) {
                        img.remove();
                    }
                } catch (e) {
                    // ignore
                }
            };
        }

        // Place the preview after any icon but before the title
        const icon = card.querySelector('.resource-card-icon');
        if (icon && icon.nextSibling) {
            card.insertBefore(img, icon.nextSibling);
        } else if (icon) {
            card.appendChild(img);
        } else {
            card.insertBefore(img, card.firstChild);
        }
    });
}

// Helper: get the element to show/hide for a given card.
// On news.html cards are wrapped in <a class="card-link">, on resources.html they are standalone.
function getToggleTarget(card) {
    const parent = card.parentElement;
    return (parent && parent.classList.contains('card-link')) ? parent : card;
}

function filterResources(searchTerm) {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    
    // Use requestAnimationFrame for smoother rendering
    requestAnimationFrame(() => {
        cards.forEach(card => {
            const title = card.querySelector('h3')?.textContent.toLowerCase() || '';
            const paragraphs = Array.from(card.querySelectorAll('p')).map(p => p.textContent).join(' ').toLowerCase();
            const tags = Array.from(card.querySelectorAll('.tag')).map(tag => tag.textContent.toLowerCase()).join(' ');

            const matches = title.includes(searchTerm) ||
                           paragraphs.includes(searchTerm) ||
                           tags.includes(searchTerm);

            getToggleTarget(card).style.display = matches ? '' : 'none';
        });

        updateVisibleCount();
    });
}

function updateVisibleCount() {
    // Use cached cards or query if not available
    const cards = domCache.cards.length > 0 ? domCache.cards : document.querySelectorAll('.resource-card');
    let visibleCount = 0;

    cards.forEach(card => {
        if (getToggleTarget(card).style.display !== 'none') {
            visibleCount++;
        }
    });

    const countElement = document.getElementById('visibleCount');
    if (countElement) {
        countElement.textContent = visibleCount;
    }
}

// =========================================================================
// DARK MODE
// =========================================================================

function initThemeToggle() {
    // Check saved preference or system preference
    const saved = localStorage.getItem('theme');
    if (saved === 'dark') {
        document.documentElement.setAttribute('data-theme', 'dark');
    } else if (saved === 'light') {
        document.documentElement.setAttribute('data-theme', 'light');
    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
        document.documentElement.setAttribute('data-theme', 'dark');
    }

    // Find the toggle button (inserted via HTML)
    const toggle = document.querySelector('.theme-toggle');
    if (toggle) {
        updateToggleIcon(toggle);
        toggle.addEventListener('click', function() {
            const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
            if (isDark) {
                document.documentElement.setAttribute('data-theme', 'light');
                localStorage.setItem('theme', 'light');
            } else {
                document.documentElement.setAttribute('data-theme', 'dark');
                localStorage.setItem('theme', 'dark');
            }
            updateToggleIcon(this);
        });
    }
}

function updateToggleIcon(btn) {
    const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
    btn.textContent = isDark ? '☀️' : '🌙';
    btn.setAttribute('aria-label', isDark ? 'Switch to light mode' : 'Switch to dark mode');
}

// =========================================================================
// SEARCH SUGGESTIONS / AUTOCOMPLETE
// =========================================================================

function initSearchSuggestions() {
    const input = domCache.searchInput;
    if (!input) return;

    // Wrap input in search-wrapper for positioning
    const wrapper = document.createElement('div');
    wrapper.className = 'search-wrapper';
    input.parentNode.insertBefore(wrapper, input);
    wrapper.appendChild(input);

    // Create suggestions dropdown
    const dropdown = document.createElement('div');
    dropdown.className = 'search-suggestions';
    dropdown.setAttribute('role', 'listbox');
    dropdown.id = 'searchSuggestions';
    wrapper.appendChild(dropdown);

    input.setAttribute('role', 'combobox');
    input.setAttribute('aria-autocomplete', 'list');
    input.setAttribute('aria-controls', 'searchSuggestions');
    input.setAttribute('aria-expanded', 'false');

    // Build suggestion index from cards
    const suggestions = buildSuggestionIndex();
    let highlightIndex = -1;

    const debouncedSuggest = debounce(function() {
        const query = input.value.trim().toLowerCase();
        if (query.length < 2) {
            closeSuggestions();
            return;
        }

        const matches = suggestions.filter(s =>
            s.text.toLowerCase().includes(query)
        ).slice(0, 8);

        if (matches.length === 0) {
            closeSuggestions();
            return;
        }

        dropdown.innerHTML = '';
        matches.forEach((match, i) => {
            const div = document.createElement('div');
            div.className = 'search-suggestion';
            div.setAttribute('role', 'option');
            div.dataset.value = match.text;
            div.innerHTML = `<span>${sanitize(match.text)}</span><span class="suggestion-type">${sanitize(match.type)}</span>`;
            div.addEventListener('mousedown', function(e) {
                e.preventDefault();
                input.value = match.text;
                closeSuggestions();
                filterResources(match.text.toLowerCase());
            });
            dropdown.appendChild(div);
        });

        highlightIndex = -1;
        dropdown.classList.add('visible');
        input.setAttribute('aria-expanded', 'true');
    }, 100);

    input.addEventListener('input', debouncedSuggest);

    input.addEventListener('keydown', function(e) {
        const items = dropdown.querySelectorAll('.search-suggestion');
        if (!dropdown.classList.contains('visible') || items.length === 0) return;

        if (e.key === 'ArrowDown') {
            e.preventDefault();
            highlightIndex = Math.min(highlightIndex + 1, items.length - 1);
            updateHighlight(items, highlightIndex);
        } else if (e.key === 'ArrowUp') {
            e.preventDefault();
            highlightIndex = Math.max(highlightIndex - 1, 0);
            updateHighlight(items, highlightIndex);
        } else if (e.key === 'Enter' && highlightIndex >= 0) {
            e.preventDefault();
            input.value = items[highlightIndex].dataset.value;
            closeSuggestions();
            filterResources(input.value.toLowerCase());
        } else if (e.key === 'Escape') {
            closeSuggestions();
        }
    });

    input.addEventListener('blur', function() {
        setTimeout(closeSuggestions, 150);
    });

    function closeSuggestions() {
        dropdown.classList.remove('visible');
        dropdown.innerHTML = '';
        highlightIndex = -1;
        input.setAttribute('aria-expanded', 'false');
    }

    function updateHighlight(items, index) {
        items.forEach(item => item.classList.remove('highlighted'));
        if (index >= 0 && index < items.length) {
            items[index].classList.add('highlighted');
            items[index].scrollIntoView({ block: 'nearest' });
        }
    }
}

function buildSuggestionIndex() {
    const seen = new Set();
    const suggestions = [];
    const cards = document.querySelectorAll('.resource-card');

    cards.forEach(card => {
        // Add card titles
        const title = card.querySelector('h3')?.textContent.trim();
        if (title && !seen.has(title.toLowerCase())) {
            seen.add(title.toLowerCase());
            suggestions.push({ text: title, type: 'Resource' });
        }

        // Add tags
        card.querySelectorAll('.tag').forEach(tag => {
            const t = tag.textContent.trim();
            if (t && !seen.has(t.toLowerCase())) {
                seen.add(t.toLowerCase());
                suggestions.push({ text: t, type: 'Tag' });
            }
        });
    });

    return suggestions;
}

// =========================================================================
// SOCIAL SHARING BUTTONS (News page)
// =========================================================================

function initShareButtons() {
    if (!document.body.classList.contains('news-page')) return;

    document.querySelectorAll('.resource-card').forEach(card => {
        const cardLink = card.closest('.card-link');
        if (!cardLink) return;

        const url = cardLink.href;
        const title = card.querySelector('h3')?.textContent.trim() || '';
        const encodedUrl = encodeURIComponent(url);
        const encodedTitle = encodeURIComponent(title);

        const container = document.createElement('div');
        container.className = 'share-buttons';

        container.innerHTML =
            `<a href="https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}" class="share-btn share-btn--linkedin" target="_blank" rel="noopener noreferrer" aria-label="Share on LinkedIn" title="Share on LinkedIn">in</a>` +
            `<a href="https://twitter.com/intent/tweet?url=${encodedUrl}&text=${encodedTitle}" class="share-btn share-btn--twitter" target="_blank" rel="noopener noreferrer" aria-label="Share on X" title="Share on X">X</a>` +
            `<a href="https://bsky.app/intent/compose?text=${encodedTitle}%20${encodedUrl}" class="share-btn share-btn--bluesky" target="_blank" rel="noopener noreferrer" aria-label="Share on Bluesky" title="Share on Bluesky">🦋</a>` +
            `<a href="https://www.reddit.com/submit?url=${encodedUrl}&title=${encodedTitle}" class="share-btn share-btn--reddit" target="_blank" rel="noopener noreferrer" aria-label="Share on Reddit" title="Share on Reddit">r/</a>`;

        // Prevent share button clicks from navigating the parent card-link
        container.addEventListener('click', function(e) {
            e.stopPropagation();
        });

        card.appendChild(container);
    });
}


